### ISSUE TITLE
Fix typos in the Readme.md file.

### ISSUE THREAD

**Issue by michelvosje** [michelvosje/Hacktoberfest-2016-Game#6]
Some typos were introduced in the Readme.md file and need to be fixed.

**Comment by krisnotchris** [comment]
Can I work on this?

**Comment by michelvosje** [comment]
Sry has been done by vlaze. Wanted to create a ticket 2 days ago. But he fixed it before i created the ticket...

**Comment by krisnotchris** [comment]
Ah man. There are still some formatting issues and incorrect uses of words.
I would be happy to further edit it unless you are satisfied.


On October 16, 2016 at 2:31:10 PM, Michel van Os (notifications@github.com)
wrote:

Closed #6 <https://github.com/michelvosje/Hacktoberfest-2016-Game/issues/6>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/michelvosje/Hacktoberfest-2016-Game/issues/6#event-825190973>,
or mute the thread

**Comment by vlaze** [comment]
@krisnotchris Yes, I think I left some errors behind. English is not my first language and I did a very quick fixing of the main errors. You can reopen a new issue asking for a grammar 're-revision', then feel free to correct what you see! :grin:

**Comment by krisnotchris** [comment]
Alright cool :) I'll see what I can come up with after I get off work today!
